<?php

namespace App\DataFixtures;

use App\Entity\Product\Product;
use DateTimeImmutable;
use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Persistence\ObjectManager;

class ProductFixtures extends Fixture
{
    const PRODUCTS = [
        [
            "id" => "90086",
            "div_name" => "Печатающие устройства",
            "type_name" => "МФУ (Многофункциональное устройство)",
            "vendor_name" => "Kyocera",
            "name" => "ECOSYS M2040",
            "art" => "90086",
            "printing_technology" => "Лазерная",
            "printing_type" => "Монохромная",
            "printing_resource" => "",
            "printing_resource_ed_izm" => "страниц",
            "printing_speed" => "40",
            "printing_speed_ed_izm" => "стр/мин. А4",
            "cartridge_type" => "Не выбран",
            "color_black" => "0",
            "color_magenta" => "0",
            "color_yellow" => "0",
            "color_cyan" => "0",
            "color_white" => "0",
            "color_transparent" => "0",
            "format_a0" => "0",
            "format_a1" => "0",
            "format_a2" => "0",
            "format_a3" => "0",
            "format_a4" => "1"
        ],
        [
            "id" => "90127",
            "div_name" => "Картриджи и блоки",
            "type_name" => "Драм-картриджи",
            "vendor_name" => "Kyocera",
            "name" => "DK-1150 Drum",
            "art" => "90127",
            "printing_technology" => "Лазерная",
            "printing_type" => "Монохромная",
            "printing_resource" => "100000",
            "printing_resource_ed_izm" => "страниц",
            "printing_speed" => "",
            "printing_speed_ed_izm" => "стр/мин. А3",
            "cartridge_type" => "DK (драм-картридж)",
            "color_black" => "1",
            "color_magenta" => "0",
            "color_yellow" => "0",
            "color_cyan" => "0",
            "color_white" => "0",
            "color_transparent" => "0",
            "format_a0" => "0",
            "format_a1" => "0",
            "format_a2" => "0",
            "format_a3" => "0",
            "format_a4" => "1"
        ],
        [
            "id" => "90136",
            "div_name" => "Картриджи и блоки",
            "type_name" => "Блоки  проявки",
            "vendor_name" => "Kyocera",
            "name" => "DV-1150",
            "art" => "90136",
            "printing_technology" => "Лазерная",
            "printing_type" => "Монохромная",
            "printing_resource" => "",
            "printing_resource_ed_izm" => "страниц",
            "printing_speed" => "",
            "printing_speed_ed_izm" => "стр/мин. А3",
            "cartridge_type" => "DV (девелопер-картридж)",
            "color_black" => "1",
            "color_magenta" => "0",
            "color_yellow" => "0",
            "color_cyan" => "0",
            "color_white" => "0",
            "color_transparent" => "0",
            "format_a0" => "0",
            "format_a1" => "0",
            "format_a2" => "0",
            "format_a3" => "0",
            "format_a4" => "1"
        ],
        [
            "id" => "90733",
            "div_name" => "Картриджи и блоки",
            "type_name" => "Картриджи для лазерных печатающих устройств",
            "vendor_name" => "Kyocera",
            "name" => "TK-1170",
            "art" => "90733",
            "printing_technology" => "Лазерная",
            "printing_type" => "Монохромная",
            "printing_resource" => "7200",
            "printing_resource_ed_izm" => "страниц",
            "printing_speed" => "",
            "printing_speed_ed_izm" => "стр/мин. А4",
            "cartridge_type" => "Туба (Туба с тонером)",
            "color_black" => "0",
            "color_magenta" => "0",
            "color_yellow" => "0",
            "color_cyan" => "0",
            "color_white" => "0",
            "color_transparent" => "0",
            "format_a0" => "0",
            "format_a1" => "0",
            "format_a2" => "0",
            "format_a3" => "0",
            "format_a4" => "1"
        ],
        [
            "id" => "90821",
            "div_name" => "Картриджи и блоки",
            "type_name" => "Картриджи для лазерных печатающих устройств",
            "vendor_name" => "Kyocera",
            "name" => "Тонер-картридж Kyocera ECOSYS M2040 TK-1170 (7.2k) БУЛАТ s-Line",
            "art" => "DFKYEM2040030",
            "printing_technology" => "Лазерная",
            "printing_type" => "Монохромная",
            "printing_resource" => "7200",
            "printing_resource_ed_izm" => "страниц",
            "printing_speed" => "",
            "printing_speed_ed_izm" => "стр/мин. А3",
            "cartridge_type" => "Туба (Туба с тонером)",
            "color_black" => "1",
            "color_magenta" => "0",
            "color_yellow" => "0",
            "color_cyan" => "0",
            "color_white" => "0",
            "color_transparent" => "0",
            "format_a0" => "0",
            "format_a1" => "0",
            "format_a2" => "0",
            "format_a3" => "0",
            "format_a4" => "1"
        ],
        [
            "id" => "97138",
            "div_name" => "Картриджи и блоки",
            "type_name" => "Бункеры для отработанного тонера",
            "vendor_name" => "Kyocera",
            "name" => "Бункер для отработанного тонера Kyocera WT-861",
            "art" => "PAKYTA6500010",
            "printing_technology" => "Лазерная",
            "printing_type" => "Монохромная",
            "printing_resource" => "",
            "printing_resource_ed_izm" => "страниц",
            "printing_speed" => "",
            "printing_speed_ed_izm" => "стр/мин. А3",
            "cartridge_type" => "Не выбран",
            "color_black" => "1",
            "color_magenta" => "0",
            "color_yellow" => "0",
            "color_cyan" => "0",
            "color_white" => "0",
            "color_transparent" => "0",
            "format_a0" => "0",
            "format_a1" => "0",
            "format_a2" => "0",
            "format_a3" => "0",
            "format_a4" => "1"
        ],
        [
            "id" => "97410",
            "div_name" => "Картриджи и блоки",
            "type_name" => "Драм-картриджи",
            "vendor_name" => "Kyocera",
            "name" => "Драм-юнит Kyocera ECOSYS P2235/P2335 DK-1150 (302RV93010) (100k) БУЛАТ s-Line",
            "art" => "DFKYEP2235040",
            "printing_technology" => "Лазерная",
            "printing_type" => "Монохромная",
            "printing_resource" => "100000",
            "printing_resource_ed_izm" => "страниц",
            "printing_speed" => "",
            "printing_speed_ed_izm" => "стр/мин. А3",
            "cartridge_type" => "DK (драм-картридж)",
            "color_black" => "1",
            "color_magenta" => "0",
            "color_yellow" => "0",
            "color_cyan" => "0",
            "color_white" => "0",
            "color_transparent" => "0",
            "format_a0" => "0",
            "format_a1" => "0",
            "format_a2" => "0",
            "format_a3" => "0",
            "format_a4" => "1"
        ],
        [
            "id" => "104505",
            "div_name" => "Картриджи и блоки",
            "type_name" => "Блоки  проявки",
            "vendor_name" => "Kyocera",
            "name" => "Блок проявки Kyocera ECOSYS P2040/M2040/P2235 DV-1150 (302RV93020) (100k)",
            "art" => "DFKYEP2040100",
            "printing_technology" => "Лазерная",
            "printing_type" => "Монохромная",
            "printing_resource" => "100000",
            "printing_resource_ed_izm" => "страниц",
            "printing_speed" => "",
            "printing_speed_ed_izm" => "стр/мин. А3",
            "cartridge_type" => "Не выбран",
            "color_black" => "1",
            "color_magenta" => "0",
            "color_yellow" => "0",
            "color_cyan" => "0",
            "color_white" => "0",
            "color_transparent" => "0",
            "format_a0" => "0",
            "format_a1" => "0",
            "format_a2" => "0",
            "format_a3" => "0",
            "format_a4" => "1"
        ],
        [
            "id" => "104655",
            "div_name" => "Картриджи и блоки",
            "type_name" => "Блоки лент переноса изображения",
            "vendor_name" => "Xerox",
            "name" => "Блок переноса изображения Xerox WorkCentre Pro 4110/4590/Xerox D95/D110 064K92841/64K91844/064K91845/064K91847/064K91848/064K91849/064K92680/064K92681/064K92682/ 064K92840/544P24864 (R)",
            "art" => "DLRXWC4110020",
            "printing_technology" => "Лазерная",
            "printing_type" => "Монохромная",
            "printing_resource" => "",
            "printing_resource_ed_izm" => "страниц",
            "printing_speed" => "",
            "printing_speed_ed_izm" => "стр/мин. А3",
            "cartridge_type" => "Не выбран",
            "color_black" => "0",
            "color_magenta" => "0",
            "color_yellow" => "0",
            "color_cyan" => "0",
            "color_white" => "0",
            "color_transparent" => "0",
            "format_a0" => "0",
            "format_a1" => "0",
            "format_a2" => "0",
            "format_a3" => "1",
            "format_a4" => "1"
        ],
        [
            "id" => "105571",
            "div_name" => "Картриджи и блоки",
            "type_name" => "Термоузлы",
            "vendor_name" => "Kyocera",
            "name" => "Термоузел Kyocera ECOSYS M2040 (печь в сборе) FK-1150 302RV93050",
            "art" => "DMKYEM2040030",
            "printing_technology" => "Лазерная",
            "printing_type" => "Монохромная",
            "printing_resource" => "",
            "printing_resource_ed_izm" => "страниц",
            "printing_speed" => "",
            "printing_speed_ed_izm" => "стр/мин. А3",
            "cartridge_type" => "Не выбран",
            "color_black" => "0",
            "color_magenta" => "0",
            "color_yellow" => "0",
            "color_cyan" => "0",
            "color_white" => "0",
            "color_transparent" => "0",
            "format_a0" => "0",
            "format_a1" => "0",
            "format_a2" => "0",
            "format_a3" => "0",
            "format_a4" => "1"
        ],
        [
            "id" => "105760",
            "div_name" => "Картриджи и блоки",
            "type_name" => "Блоки  проявки",
            "vendor_name" => "Xerox",
            "name" => "Блок проявки Xerox 4110/D95 (Developer Housing Assembly) 848K13701/848K52385 (R)",
            "art" => "DFRX004110010",
            "printing_technology" => "Лазерная",
            "printing_type" => "Монохромная",
            "printing_resource" => "",
            "printing_resource_ed_izm" => "страниц",
            "printing_speed" => "",
            "printing_speed_ed_izm" => "стр/мин. А3",
            "cartridge_type" => "PCU (блок проявки вместе с барабаном)",
            "color_black" => "0",
            "color_magenta" => "0",
            "color_yellow" => "0",
            "color_cyan" => "0",
            "color_white" => "0",
            "color_transparent" => "0",
            "format_a0" => "0",
            "format_a1" => "0",
            "format_a2" => "0",
            "format_a3" => "1",
            "format_a4" => "1"
        ],
        [
            "id" => "75145",
            "div_name" => "Тонеры, девелоперы и чернила",
            "type_name" => "Тонеры",
            "vendor_name" => "Kyocera",
            "name" => "Тонер Kyocera KB02.1 банка 1кг",
            "art" => "AAMT0KB021020",
            "printing_technology" => "Лазерная",
            "printing_type" => "Монохромная",
            "printing_resource" => "",
            "printing_resource_ed_izm" => "страниц",
            "printing_speed" => "",
            "printing_speed_ed_izm" => "стр/мин. А3",
            "cartridge_type" => "Не выбран",
            "color_black" => "1",
            "color_magenta" => "0",
            "color_yellow" => "0",
            "color_cyan" => "0",
            "color_white" => "0",
            "color_transparent" => "0",
            "format_a0" => "0",
            "format_a1" => "0",
            "format_a2" => "0",
            "format_a3" => "0",
            "format_a4" => "0"
        ],
        [
            "id" => "90289",
            "div_name" => "Тонеры, девелоперы и чернила",
            "type_name" => "Тонеры",
            "vendor_name" => "Kyocera",
            "name" => "Тонер Kyocera ECOSYS M2040/P2040 банка 240г TK-1170/1160 БУЛАТ s-Line",
            "art" => "DAKYEM2040010",
            "printing_technology" => "Лазерная",
            "printing_type" => "Монохромная",
            "printing_resource" => "",
            "printing_resource_ed_izm" => "страниц",
            "printing_speed" => "",
            "printing_speed_ed_izm" => "стр/мин. А3",
            "cartridge_type" => "Не выбран",
            "color_black" => "1",
            "color_magenta" => "0",
            "color_yellow" => "0",
            "color_cyan" => "0",
            "color_white" => "0",
            "color_transparent" => "0",
            "format_a0" => "0",
            "format_a1" => "0",
            "format_a2" => "0",
            "format_a3" => "0",
            "format_a4" => "1"
        ],
        [
            "id" => "103834",
            "div_name" => "Тонеры, девелоперы и чернила",
            "type_name" => "Девелоперы",
            "vendor_name" => "Xerox",
            "name" => "Девелопер Xerox D95/Xerox 4110 005R00704/505S00034/675K16880 банка 700г БУЛАТ s-Line",
            "art" => "DAHP000D95010",
            "printing_technology" => "Лазерная",
            "printing_type" => "Монохромная",
            "printing_resource" => "",
            "printing_resource_ed_izm" => "страниц",
            "printing_speed" => "",
            "printing_speed_ed_izm" => "стр/мин. А3",
            "cartridge_type" => "Не выбран",
            "color_black" => "0",
            "color_magenta" => "0",
            "color_yellow" => "0",
            "color_cyan" => "0",
            "color_white" => "0",
            "color_transparent" => "0",
            "format_a0" => "0",
            "format_a1" => "0",
            "format_a2" => "0",
            "format_a3" => "1",
            "format_a4" => "1"
        ],
        [
            "id" => "96112",
            "div_name" => "Материалы для восстановления картриджей и блоков",
            "type_name" => "Ракели",
            "vendor_name" => "Kyocera",
            "name" => "Ракель Kyocera ECOSYS M2040/P2040/P2235 wiper",
            "art" => "DGKYEM2040020",
            "printing_technology" => "Лазерная",
            "printing_type" => "Монохромная",
            "printing_resource" => "",
            "printing_resource_ed_izm" => "страниц",
            "printing_speed" => "",
            "printing_speed_ed_izm" => "стр/мин. А3",
            "cartridge_type" => "Не выбран",
            "color_black" => "0",
            "color_magenta" => "0",
            "color_yellow" => "0",
            "color_cyan" => "0",
            "color_white" => "0",
            "color_transparent" => "0",
            "format_a0" => "0",
            "format_a1" => "0",
            "format_a2" => "0",
            "format_a3" => "0",
            "format_a4" => "1"
        ],
        [
            "id" => "97968",
            "div_name" => "Материалы для восстановления картриджей и блоков",
            "type_name" => "Комплектующие к термоузлам",
            "vendor_name" => "N/A",
            "name" => "Термопленка Kyocera ECOSYS M2040/P2235 БУЛАТ m-Line",
            "art" => "DTKYEM2040020",
            "printing_technology" => "Лазерная",
            "printing_type" => "Монохромная",
            "printing_resource" => "",
            "printing_resource_ed_izm" => "страниц",
            "printing_speed" => "",
            "printing_speed_ed_izm" => "стр/мин. А3",
            "cartridge_type" => "Не выбран",
            "color_black" => "0",
            "color_magenta" => "0",
            "color_yellow" => "0",
            "color_cyan" => "0",
            "color_white" => "0",
            "color_transparent" => "0",
            "format_a0" => "0",
            "format_a1" => "0",
            "format_a2" => "0",
            "format_a3" => "0",
            "format_a4" => "1"
        ],
        [
            "id" => "99898",
            "div_name" => "Материалы для восстановления картриджей и блоков",
            "type_name" => "Чипы",
            "vendor_name" => "Kyocera",
            "name" => "Чип Kyocera ECOSYS M2040 TK-1170 (7.2k)",
            "art" => "DUKYEM2040030",
            "printing_technology" => "Лазерная",
            "printing_type" => "Монохромная",
            "printing_resource" => "7200",
            "printing_resource_ed_izm" => "страниц",
            "printing_speed" => "",
            "printing_speed_ed_izm" => "стр/мин. А3",
            "cartridge_type" => "Не выбран",
            "color_black" => "1",
            "color_magenta" => "0",
            "color_yellow" => "0",
            "color_cyan" => "0",
            "color_white" => "0",
            "color_transparent" => "0",
            "format_a0" => "0",
            "format_a1" => "0",
            "format_a2" => "0",
            "format_a3" => "0",
            "format_a4" => "1"
        ],
        [
            "id" => "101533",
            "div_name" => "Материалы для восстановления картриджей и блоков",
            "type_name" => "Ремкомплекты",
            "vendor_name" => "Kyocera",
            "name" => "Ремонтный комплект Kyocera ECOSYS P2235/P2040/M2040 DV-1150 OEM (тех. упаковка)",
            "art" => "ARKYEP2235010",
            "printing_technology" => "Лазерная",
            "printing_type" => "Монохромная",
            "printing_resource" => "",
            "printing_resource_ed_izm" => "страниц",
            "printing_speed" => "",
            "printing_speed_ed_izm" => "стр/мин. А3",
            "cartridge_type" => "Не выбран",
            "color_black" => "1",
            "color_magenta" => "0",
            "color_yellow" => "0",
            "color_cyan" => "0",
            "color_white" => "0",
            "color_transparent" => "0",
            "format_a0" => "0",
            "format_a1" => "0",
            "format_a2" => "0",
            "format_a3" => "0",
            "format_a4" => "1"
        ],
        [
            "id" => "101922",
            "div_name" => "Материалы для восстановления картриджей и блоков",
            "type_name" => "Фоторецепторы",
            "vendor_name" => "Kyocera",
            "name" => "Фоторецептор Kyocera ECOSYS P2235 DK-1150",
            "art" => "DCKYEP2235030",
            "printing_technology" => "Лазерная",
            "printing_type" => "Монохромная",
            "printing_resource" => "",
            "printing_resource_ed_izm" => "страниц",
            "printing_speed" => "",
            "printing_speed_ed_izm" => "стр/мин. А3",
            "cartridge_type" => "Не выбран",
            "color_black" => "0",
            "color_magenta" => "0",
            "color_yellow" => "0",
            "color_cyan" => "0",
            "color_white" => "0",
            "color_transparent" => "0",
            "format_a0" => "0",
            "format_a1" => "0",
            "format_a2" => "0",
            "format_a3" => "0",
            "format_a4" => "1"
        ],
        [
            "id" => "103619",
            "div_name" => "Материалы для восстановления картриджей и блоков",
            "type_name" => "ЗИП",
            "vendor_name" => "Kyocera",
            "name" => "Насадка на рол отд/б (прозрачная) Kyocera FS-1028/2000/4100/ECOSYS M2030 302BR06520/302F909170/302F909171 БУЛАТ m-Line",
            "art" => "AVKYFS1028090",
            "printing_technology" => "Лазерная",
            "printing_type" => "Монохромная",
            "printing_resource" => "",
            "printing_resource_ed_izm" => "страниц",
            "printing_speed" => "",
            "printing_speed_ed_izm" => "стр/мин. А3",
            "cartridge_type" => "Не выбран",
            "color_black" => "0",
            "color_magenta" => "0",
            "color_yellow" => "0",
            "color_cyan" => "0",
            "color_white" => "0",
            "color_transparent" => "0",
            "format_a0" => "0",
            "format_a1" => "0",
            "format_a2" => "0",
            "format_a3" => "0",
            "format_a4" => "1"
        ],
        [
            "id" => "106408",
            "div_name" => "Материалы для восстановления картриджей и блоков",
            "type_name" => "Комплектующие к термоузлам",
            "vendor_name" => "Kyocera",
            "name" => "Тканевая накладка прижимной планки (white) Kyocera ECOSYS M2040/M2135/P2235 (накладка+масло)",
            "art" => "AOKYEM2040080",
            "printing_technology" => "Лазерная",
            "printing_type" => "Монохромная",
            "printing_resource" => "",
            "printing_resource_ed_izm" => "страниц",
            "printing_speed" => "",
            "printing_speed_ed_izm" => "стр/мин. А3",
            "cartridge_type" => "Не выбран",
            "color_black" => "0",
            "color_magenta" => "0",
            "color_yellow" => "0",
            "color_cyan" => "0",
            "color_white" => "0",
            "color_transparent" => "0",
            "format_a0" => "0",
            "format_a1" => "0",
            "format_a2" => "0",
            "format_a3" => "0",
            "format_a4" => "1"
        ],
        [
            "id" => "96474",
            "div_name" => "Оборудование и принадлежности для сервиса",
            "type_name" => "Масла и смазки",
            "vendor_name" => "N/A",
            "name" => "Смазка для термопленки CK-0551 тюбик 10г",
            "art" => "PDZZ000000110",
            "printing_technology" => "Лазерная",
            "printing_type" => "Не выбран",
            "printing_resource" => "",
            "printing_resource_ed_izm" => "страниц",
            "printing_speed" => "",
            "printing_speed_ed_izm" => "стр/мин. А3",
            "cartridge_type" => "Не выбран",
            "color_black" => "0",
            "color_magenta" => "0",
            "color_yellow" => "0",
            "color_cyan" => "0",
            "color_white" => "0",
            "color_transparent" => "0",
            "format_a0" => "0",
            "format_a1" => "0",
            "format_a2" => "0",
            "format_a3" => "0",
            "format_a4" => "0"
        ],
        [
            "id" => "96482",
            "div_name" => "Оборудование и принадлежности для сервиса",
            "type_name" => "Инструмент",
            "vendor_name" => "Bulat",
            "name" => "Воронка для банки БУЛАТ",
            "art" => "PIZZ000000270",
            "printing_technology" => "Не выбрана",
            "printing_type" => "Не выбран",
            "printing_resource" => "",
            "printing_resource_ed_izm" => "страниц",
            "printing_speed" => "",
            "printing_speed_ed_izm" => "стр/мин. А3",
            "cartridge_type" => "Не выбран",
            "color_black" => "0",
            "color_magenta" => "0",
            "color_yellow" => "0",
            "color_cyan" => "0",
            "color_white" => "0",
            "color_transparent" => "0",
            "format_a0" => "0",
            "format_a1" => "0",
            "format_a2" => "0",
            "format_a3" => "0",
            "format_a4" => "0"
        ],
        [
            "id" => "96484",
            "div_name" => "Оборудование и принадлежности для сервиса",
            "type_name" => "Инструмент",
            "vendor_name" => "N/A",
            "name" => "Двухсторонний скотч для фиксации sealing/recovery blade 5 мм*50м",
            "art" => "PQZZ000000530",
            "printing_technology" => "Не выбрана",
            "printing_type" => "Не выбран",
            "printing_resource" => "",
            "printing_resource_ed_izm" => "страниц",
            "printing_speed" => "",
            "printing_speed_ed_izm" => "стр/мин. А3",
            "cartridge_type" => "Не выбран",
            "color_black" => "0",
            "color_magenta" => "0",
            "color_yellow" => "0",
            "color_cyan" => "0",
            "color_white" => "0",
            "color_transparent" => "0",
            "format_a0" => "0",
            "format_a1" => "0",
            "format_a2" => "0",
            "format_a3" => "0",
            "format_a4" => "0"
        ],
        [
            "id" => "101056",
            "div_name" => "Оборудование и принадлежности для сервиса",
            "type_name" => "Пылесосы и ЗИП к ним",
            "vendor_name" => "N/A",
            "name" => "Пылесос SVC220 800W",
            "art" => "PAZZ000000030",
            "printing_technology" => "Не выбрана",
            "printing_type" => "Не выбран",
            "printing_resource" => "",
            "printing_resource_ed_izm" => "страниц",
            "printing_speed" => "",
            "printing_speed_ed_izm" => "стр/мин. А3",
            "cartridge_type" => "Не выбран",
            "color_black" => "0",
            "color_magenta" => "0",
            "color_yellow" => "0",
            "color_cyan" => "0",
            "color_white" => "0",
            "color_transparent" => "0",
            "format_a0" => "0",
            "format_a1" => "0",
            "format_a2" => "0",
            "format_a3" => "0",
            "format_a4" => "0"
        ],
        [
            "id" => "101057",
            "div_name" => "Оборудование и принадлежности для сервиса",
            "type_name" => "Пылесосы и ЗИП к ним",
            "vendor_name" => "N/A",
            "name" => "Фильтр для SVC220",
            "art" => "PBZZ000000050",
            "printing_technology" => "Не выбрана",
            "printing_type" => "Не выбран",
            "printing_resource" => "",
            "printing_resource_ed_izm" => "страниц",
            "printing_speed" => "",
            "printing_speed_ed_izm" => "стр/мин. А3",
            "cartridge_type" => "Не выбран",
            "color_black" => "0",
            "color_magenta" => "0",
            "color_yellow" => "0",
            "color_cyan" => "0",
            "color_white" => "0",
            "color_transparent" => "0",
            "format_a0" => "0",
            "format_a1" => "0",
            "format_a2" => "0",
            "format_a3" => "0",
            "format_a4" => "0"
        ],
        [
            "id" => "101221",
            "div_name" => "Оборудование и принадлежности для сервиса",
            "type_name" => "Масла и смазки",
            "vendor_name" => "Kyocera",
            "name" => "Фьюзерное масло для Kyocera/Ricoh шприц 1 мл",
            "art" => "PDKYFK1150020",
            "printing_technology" => "Не выбрана",
            "printing_type" => "Не выбран",
            "printing_resource" => "",
            "printing_resource_ed_izm" => "страниц",
            "printing_speed" => "",
            "printing_speed_ed_izm" => "стр/мин. А3",
            "cartridge_type" => "Не выбран",
            "color_black" => "0",
            "color_magenta" => "0",
            "color_yellow" => "0",
            "color_cyan" => "0",
            "color_white" => "0",
            "color_transparent" => "0",
            "format_a0" => "0",
            "format_a1" => "0",
            "format_a2" => "0",
            "format_a3" => "0",
            "format_a4" => "0"
        ],
        [
            "id" => "104666",
            "div_name" => "Оборудование и принадлежности для сервиса",
            "type_name" => "Пылесосы и ЗИП к ним",
            "vendor_name" => "N/A",
            "name" => "Шланг для пылесосов 3M/SVC220",
            "art" => "PBZZ000000230",
            "printing_technology" => "Не выбрана",
            "printing_type" => "Не выбран",
            "printing_resource" => "",
            "printing_resource_ed_izm" => "страниц",
            "printing_speed" => "",
            "printing_speed_ed_izm" => "стр/мин. А3",
            "cartridge_type" => "Не выбран",
            "color_black" => "0",
            "color_magenta" => "0",
            "color_yellow" => "0",
            "color_cyan" => "0",
            "color_white" => "0",
            "color_transparent" => "0",
            "format_a0" => "0",
            "format_a1" => "0",
            "format_a2" => "0",
            "format_a3" => "0",
            "format_a4" => "0"
        ],
        [
            "id" => "104985",
            "div_name" => "Оборудование и принадлежности для сервиса",
            "type_name" => "Чистящие средства",
            "vendor_name" => "N/A",
            "name" => "Средство для очистки и восст. резиновых поверхностей Platen Clean (аэрозоль) 520мл",
            "art" => "PCZZ000000500",
            "printing_technology" => "Лазерная",
            "printing_type" => "Не выбран",
            "printing_resource" => "",
            "printing_resource_ed_izm" => "страниц",
            "printing_speed" => "",
            "printing_speed_ed_izm" => "стр/мин. А3",
            "cartridge_type" => "Не выбран",
            "color_black" => "0",
            "color_magenta" => "0",
            "color_yellow" => "0",
            "color_cyan" => "0",
            "color_white" => "0",
            "color_transparent" => "0",
            "format_a0" => "0",
            "format_a1" => "0",
            "format_a2" => "0",
            "format_a3" => "0",
            "format_a4" => "0"
        ]
    ];

    public function __construct(
    )
    {
    }

    public function load(ObjectManager $manager)
    {
        foreach (self::PRODUCTS as $productFixture) {
            if ($manager->getRepository('\\App\\Entity\\Product\\Product')->findBy(['article' => $productFixture['art']])) {
                $product = $manager->getRepository('\\App\\Entity\\Product\\Product')->findOneBy(['article' => $productFixture['art']]);
            }else{
                $product = new Product();
            }

            $product->setExternalId($productFixture['id']);
            $product->setName($productFixture['name']);
            $product->setArticle($productFixture['art']);
            $product->setColorBlack($productFixture['color_black']);
            $product->setColorMagenta($productFixture['color_magenta']);
            $product->setColorYellow($productFixture['color_yellow']);
            $product->setColorCyan($productFixture['color_cyan']);
            $product->setColorWhite($productFixture['color_white']);
            $product->setColorTransparent($productFixture['color_transparent']);
            $product->setFormatA0($productFixture['format_a0']);
            $product->setFormatA1($productFixture['format_a1']);
            $product->setFormatA2($productFixture['format_a2']);
            $product->setFormatA3($productFixture['format_a3']);
            $product->setFormatA4($productFixture['format_a4']);

            $product->setCategory($manager->getRepository('\\App\\Entity\\Product\\ProductCategory')->findOneBy(['name' => $productFixture['div_name']]));
            $product->setType($manager->getRepository('\\App\\Entity\\Product\\ProductType')->findOneBy(['name' => $productFixture['type_name']]));
            $product->setBrand($manager->getRepository('\\App\\Entity\\Product\\ProductBrand')->findOneBy(['name' => $productFixture['vendor_name']]));

            $product->setCreatedAt(new DateTimeImmutable());

            $manager->persist($product);
        }

        $manager->flush();
    }
}
